import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="bg-gray-800 p-4 text-white">
          <div className="container mx-auto flex justify-between items-center">
            <Link href="/" className="text-xl font-bold">
              Classifieds
            </Link>
            <div>
              <Link href="/ads" className="mr-4 hover:text-gray-300">
                All Ads
              </Link>
              <Link href="/create-ad" className="mr-4 hover:text-gray-300">
                Post Ad
              </Link>
              {/* We can add login/logout links here later based on auth state */}
            </div>
          </div>
        </nav>
        <main className="container mx-auto mt-4">
          {children}
        </main>
      </body>
    </html>
  );
}
